name: Schedule
on:
  push:
    branches: [ master ]
  schedule:
  - cron: 0 8,18 * * *

jobs:
  daily:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download App
      uses: actions/download-artifact@v2
      with:
        name: ris-timebot
    - run: ls -al
    - name: Timesheet push time.
      run: ./ris-timebot
      env:
        TIME_EMPLOYEE: ${{ secrets.EMPLOYEE_ID }}
        TIME_PASSWORD: ${{ secrets.EMPLOYEE_PWD }}
        TIME_JOB: ${{ secrets.EMPLOYEE_JOB }}
        TIME_HOUR: 8
        TIME_SUBMIT: true
